# Generated by Django 3.1.1 on 2020-10-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20201026_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', editable=False, help_text='PLEASE KEAVE THIS FIELD EMPTY.', max_length=200),
        ),
    ]
