# Generated by Django 3.1.1 on 2021-08-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyus',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
