# Generated by Django 3.1.1 on 2021-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0003_team_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('photo', models.ImageField(upload_to='services')),
            ],
        ),
    ]
