# Generated by Django 3.1.1 on 2021-08-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0004_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='hide',
            new_name='hidden',
        ),
        migrations.RenameField(
            model_name='whyus',
            old_name='hide',
            new_name='hidden',
        ),
        migrations.AddField(
            model_name='service',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
